name: Deploy to VPS (using GHCR)

on:
  push:
    branches:
      - stabi

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker GHCR
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_AT }}
        run: |
          echo $GHCR_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/neverlateorg/never-late-api:latest .

      - name: Push Docker image
        run: |
          docker push ghcr.io/neverlateorg/never-late-api:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-publish
    env:
      GHCR_TOKEN: ${{ secrets.GHCR_AT }}
      MASTER_SSH_USER: ${{ secrets.MASTER_SSH_USER }}
      MASTER_HOST: ${{ secrets.MASTER_HOST }}
      MASTER_SSH_ENV_PATH: ${{ secrets.MASTER_SSH_ENV_PATH }}

    steps:
      - name: write ssh key to file
        run: |
          echo "${{ secrets.MASTER_SSH_KEY }}" > id_rsa
          chmod 400 id_rsa
      - name: Login to GHCR Docker
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa "${MASTER_SSH_USER}@${MASTER_HOST}" "echo $GHCR_TOKEN | docker login ghcr.io -u ${{ github.repository_owner }} --password-stdin"
      - name: Remove old image and container
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa "${MASTER_SSH_USER}@${MASTER_HOST}" "docker rm -f NeverLateAPI || true && docker rmi ghcr.io/neverlateorg/never-late-api:latest || true"
      - name: Download and run image
        run: |
          ssh -o StrictHostKeyChecking=no -i id_rsa "${MASTER_SSH_USER}@${MASTER_HOST}" "docker run -d --network=neverlate-network --name NeverLateAPI -p 3000:3000 --env-file ${MASTER_SSH_ENV_PATH} ghcr.io/neverlateorg/never-late-api:latest"
